#pragma config(StandardModel, "RVW Buggybot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/****************************************************
Name: Iniyan Joseph
Period: 3
Date: 3/11/2020
Assignment: Basketball Drills
Program Description: Robot goes back and forth to various lines
Algorithm:
1.Forward until dark
2.Forward until light
3. Back to start
4.Forward until dark
5.Forward until dark
6.Forward until light
7. Back to start
8.Forward until dark
9.Forward until dark
10.Forward until dark
11.Forward until light
12. Back to start
*******************************************************/
//Variables---------------------------------------------
int speed = 70; // speed of motors
//Functions---------------------------------------------
void fudful(); //forward until dark and forward until light
void back(); // back until start
void switchfunction(int num); //switch statement to execute fudful & back

task main()
{
	switchfunction(3);//switch function
	switchfunction(2);//switch function
	switchfunction(1);//switch function
}
//------------------------------------------------------
void fudful()//Forward until dark forward until light
{
	while(SensorValue[lightSensor] < 2000)//As long as we see white
	{
		motor[leftMotor] = speed;//Turn Left Motor Forward
		motor[rightMotor] = speed;//Turn Right Motor Forward
	}
	while(SensorValue[lightSensor] > 2000)//As long as we see black
	{
		motor[leftMotor] = speed;//Turn Left Motor Forward
		motor[rightMotor] = speed;//Turn Right Motor Forward
	}
}

void back()//Go back to start
{
	while(SensorValue[leftEncoder] >=0)//As long as the encoder is more than 0
	{
		motor[leftMotor] = -speed;//Turn Left Motor Backwards
		motor[rightMotor] = -speed;//Turn Left Motor Backwards
	}
}

void switchfunction(int num)//Function containing switch statement
{
	switch(num)//Switch Statement
	{
		case 1://First Case
			fudful();//forward until dark
							 //forward until light
		case 2://Second Case
			fudful();//forward until dark
							 //forward until light
		case 3://Third Case
			fudful();//forward until dark
							 //forward until light
			back();//back to start

	}
}
