#pragma config(StandardModel, "RVW Anemobot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/****************************************************
Name: Iniyan Joseph
Period: 3
Date: 5/8/2020
Assignment: Ruins of Atlantis
Program Description: Robot goes back and forth to various lines
Algorithm:
1. Back 0.6 meters
2. Straight 1.4 meters
3. Left to 90 degree position
4. Go straight with sonar sensor until 20 cm away
5. Back 0.4 meters
6. Right to 0 degree position
7. Straight 0.5 meters
8. Right to 91 degree position
9. Straight 1.65 meters
10. Left to 25 degree position
11. Straight 2.475 meters
12. Left to 90 degree position
13. Back 0.6 meters
14. Straight 1.9 meters
15. Right to 0 degree position
16. Straight 1.1 meters
17. Left to the 90 degree position
18. Straight 1.175 meters
19. Left to the 195 degree position
20. Straight 0.65 meters
21. Back 0.65 meters
22. Right to the -100 degree position
23. Straight 0.9 meters
24. Left to the 200 degree position
25. Straight 2.1 meters
26. Right to the -100 degree position
27. Back 0.5 meters
28. Straight 1.7 meters
29. Right to the 0 degree position
30. Straight 0.6 meters
31. Back 0.6 meters
32. Left to 90 degree position
33. Straight 0.9 meters
34. Right to the 0 degree position
35. Straight 2.3 meters
36. Right to the 100 degree position
37. Straight 1 meter
38. Back 1 meter
39. Left to the 0 degree position
40. Straight 1.2 meters
41. Left to the 90 degree position
42. Straight 1.3 meters
43. Right to the 0 degree position
44. Straight 1.4 meters
45. Left to the 113 degree position
46. Increase speed
47. Straight 2.6 meters
48. Decrease speed
49. Back 2.6 meters
50. Right to the 0 degree position
51. Back 1.6 meters
52. Left to the 113 degree position
53. Increase speed
54. Straight 1.8 meters
55. Decrease speed
56. Right to -100 degree position
57. Go straight with touchSensor
58. Left to the 185 degree position
59. Straight 0.6 meters
60. Left to the 285 degree position
61. Straight 0.5 meters
62. Right to the -205 degree position
63. Straight 1 meter
64. Right to the -105 degree position
65. Straight 0.5 meters
66. Left to the 285 degree position
67. Straight 1.65 meters
68. Right to the -195 degree position
69. Straight 1.9 meters
70. Right to the -60 degree position
71. Increase speed to clear ramp accurately
72. Straight 1.2 meters
73. Decrease speed to execute other code accurately
74. Left to the 100 degree position
75. Straight 4.4 meters
76. Right to the 0 degree position
77. Straight 5 meters
78. Back 2.5 meters
79. Left to the 305 degree position
80. Increase speed to clear ramp accurately
81. Straight 3 meters
82. Decrease speed to execute other code accurately
83. Back 0.3 meters
84. Right to the 295 degree position
85. Straight 3.2 meters
86. Stopall motors(Safeguard)
*******************************************************/
//               READ: The ways the gyros work is in a compass format.
//                     Directions are constant, so to turn, it is not
//                     Turn 90 degrees left. It is turn to the 90 degree position.
//                     The gyro sensors cannot reset to 0. Negatives are also used.
//                     This is because by using greater numbers, you must rotate multiple times
//                     By using negatives, you can only rotate to the neccesary point.
//                     In addition, the speed must be increased to properly compensate for the
//                     angle of the ramp. By increasing speed when ramping increases accuracy.
//Variables---------------------------------------------
int speed = 50;                                    //Speed variable
//Functions---------------------------------------------
void straightenc(float distance);                  // Function to go straight with encoders
void back(float distance);                         // Function to go back with encoders
void stopall();                                    // Function to stop all motors
void turnrightdeg(int degree);                     // Function to turn right
void turnleftdeg(int degree);                      // Function to turn left
task main()
{
	// 1st CheckPoint to 2nd CheckPoint
	back(0.6);                                       // Back 0.6 meters
	straightenc(1.4);                                // Straight 1.4 meters
	turnleftdeg(90);                                 // Left to the 90 Degrees position
	while(SensorValue[sonarSensor] > 20)             // As long as we are greater than 20 cm away
	{
	  motor[leftMotor] = speed;                      // Turn the right motor
	  motor[rightMotor] = speed;                     // Turn the left motor
	}
	back(0.4);                                       // Back 0.4 meters
	turnrightdeg(0);                                 // Right to the 0 position
	straightenc(0.5);                                // Straight 0.5 meters
	turnrightdeg(91);                                // Turn to the 91 degree position
	straightenc(1.65);                               // Straight 1.65 meters
	turnleftdeg(25);                                 // Left to the 25 degree position
	// 2nd CheckPoint to 3rd CheckPoint
	straightenc(2.475);                              // Straight 2.475 meters
	turnleftdeg(90);                                 // Left to the 90 degree position

	// 3rd CheckPoint to 4th CheckPoint
	back(0.6);                                       // Back 0.6 meters
	straightenc(1.9);                                // Straight 1.9 meters
	turnrightdeg(0);                                 // Right to the 0 position
	straightenc(1.1);                                // Straight 1.1 meters
	turnleftdeg(90);                                 // Left to the 90 degree position

	// 4th CheckPoint to 5th CheckPoint
	straightenc(1.175);                              // Straight 1.175 meters
	turnleftdeg(195);                                // Left to the 195 degree position
	straightenc(0.65);                               // Straight 0.65 meters
	back(0.65);                                      // Back 0.65 meters
	turnrightdeg(-100);                              // Right to the -100 position
	straightenc(0.9);                                // Straight 0.9 meters
	turnleftdeg(200);                                // Left to the 200 degree position
	straightenc(2.1);                                // Straight 2.1 meters
	turnrightdeg(-100);                              // Right to the -100 degree position
	back(0.5);                                       // Back 0.5 meters
	straightenc(1.7);                                // Straight 1.7 meters
	turnrightdeg(0);                                 // Right to the 0 degree position
	straightenc(0.6);                                // Straight 0.6 meters
	back(0.6);                                       // Back 0.6 meters
	turnleftdeg(90);                                 // Left to the 90 degree position
	straightenc(0.9);                                // Straight 0.9 meters
	turnrightdeg(0);                                 // Right to the 0 degree position
	straightenc(2.3);                                // Straight 2.3 meters

	// 5th CheckPoint to 6th CheckPoint
	turnrightdeg(100);                               // Right to the 100 degree position
	straightenc(1);                                  // Straight 1 meter
	back(1);                                         // Back 1 meter
	turnleftdeg(0);                                  // Left to the 0 degree position
	straightenc(1.2);                                // Straight 1.2 meters
	turnleftdeg(90);                                 // Left to the 90 degree position
	straightenc(1.3);                                // Straight 1.3 meters
	turnrightdeg(0);                                 // Right to the 0 degree position
	straightenc(1.4);                                // Straight 1.4 meters
	turnleftdeg(113);                                // Left to the 113 degree position
	speed=127;                                       // Increase speed to clear ramp accurately
	straightenc(2.6);                                // Straight 2.6 meters
	speed=50;                                        // Decrease speed to execute other code accurately
	back(2.6);                                       // Back 2.6 meters
	turnrightdeg(0);                                 // Right to the 0 degree position
	back(1.6);                                       // Back 1.6 meters
	turnleftdeg(113);                                // Left to the 113 degree position
	speed = 127;                                     // Increase speed to clear ramp accurately
	straightenc(1.8);                                // Straight 1.8 meters
	speed = 50;                                      // Decrease speed to execute other code accurately
	turnrightdeg(-100);                              // Right to the -100 degree position
	while(SensorValue[touchSensor] != 1)             // As long as the robot doesn't touch anything
	{
		motor[leftMotor] = speed;                      // Turn the left motor
		motor[rightMotor] = speed;                     // Turn the right motor
	}

	// 6th CheckPoint to 7th CheckPoint
	turnleftdeg(185);                                // Left to the 185 degree position
	straightenc(0.6);                                // Straight 0.6 meters
	turnleftdeg(285);                                // Left to the 285 degree position
	straightenc(0.5);                                // Straight 0.5 meters
	turnrightdeg(-205);                              // Right to the -205 degree position
	straightenc(1);                                  // Straight 1 meter
	turnrightdeg(-105);                              // Right to the -105 degree position
	straightenc(0.5);                                // Straight 0.5 meters
	turnleftdeg(285);                                // Left to the 285 degree position
	straightenc(1.65);                               // Straight 1.65 meters
	turnrightdeg(-195);                              // Right to the -195 degree position
	straightenc(1.9);                                // Straight 1.9 meters
	turnrightdeg(-60);                               // Right to the -60 degree position
	speed=127;                                       // Increase speed to clear ramp accurately
	straightenc(1.2);                                // Straight 1.2 meters
	speed=50;                                        // Decrease speed to execute other code accurately
	turnleftdeg(100);                                // Left to the 100 degree position
	straightenc(4.4);                                // Straight 4.4 meters
	turnrightdeg(0);                                 // Right to the 0 degree position
	straightenc(5);                                  // Straight 5 meters
	back(2.5);                                       // Back 2.5 meters
	turnleftdeg(305);                                // Left to the 305 degree position
	speed=127;                                       // Increase speed to clear ramp accurately
	straightenc(3);                                  // Straight 3 meters
	speed=50;                                        // Decrease speed to execute other code accurately
	back(0.3);                                       // Back 0.3 meters
	turnrightdeg(295);                               // Right to the 295 degree position
	straightenc(3.2);                                // Straight 3.2 meters
	stopall();                                       // Stopall motors(Safeguard)
}
//------------------------------------------------------

void straightenc(float distance)                   // Function body to go straight with encoders
{
	SensorValue[leftEncoder] = 0;
	while(SensorValue[leftEncoder] < (distance*833)) // As long as we are less than the conversion from encoder to meters
	{
		motor[leftMotor] = speed;                      // Turn on the left motor
		motor[rightMotor] = speed;                     // Turn on the right motor
	}
}

void back(float distance)                          // Function body to go back with encoders
{
	SensorValue[leftEncoder] = 0;
	while(SensorValue[leftEncoder] > (-distance*833)) // As long as we are greater than the conversion from encoder to meters
	{
		motor[leftMotor] = -speed;                     // Reverse the left motor
		motor[rightMotor] = -speed;                    // Reverse on the right motor
	}
}


void stopall()                                     // Function body to Stop all motors
{
	motor[leftMotor] = 0;                            // Turn off the left motor
	motor[rightMotor] = 0;                           // Turn off the right motor
}

void turnrightdeg(int degree)                      // Function body to turn right
{
	while(SensorValue[gyro] > (885/90*-degree))      // As long as we are not at the specified number of degrees
	{
		motor[leftMotor] = -speed;                     // Reverse the left motor
		motor[rightMotor] = speed;                     // Turn on the right motor
	}
}

void turnleftdeg(int degree)                      // Function body to turn left
{
	while(SensorValue[gyro] < (885/90*degree))      // As long as we are not at the specified number of degrees
	{
		motor[leftMotor] = speed;                      // Turn on the left motor
		motor[rightMotor] = -speed;                    // Reverse the right motor
	}
}
