#pragma config(StandardModel, "RVW SWERVEBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/****************************************************
Name: Iniyan Joseph
Period: 3
Date: 3/18/2020
Assignment: Robo Slalom 3 (3 Sensor)
Program Description: Follow a line
Algorithm:
1.If we see black with both the right and left sensor and the middle, stop
2.If we see black with the right sensor and not with the left sensor and the middle sensor is white, turn left
3.If we see black with the left sensor and not with the right sensor and the middle sesnor is white, turn right
4.If we see black with neither the right and left sensor and the middle sensor is black, go forward
*******************************************************/
//Variables---------------------------------------------
int speed = 70;//Set the speed of the motors
//Functions---------------------------------------------
void straight();//Declare Function to go straight
void left();//Declare Function to go left
void right();//Declare Function to go stop the robot
void stopbot();//Stop the robot

task main()
{
	while(true)
	{
	straight();//Go straight
	left();//Turn Left
	right();//Right
	stopbot();//Stop The Robot
	}
}

//Function Glossary-------------------------------------
void straight()//Function to go straight
{
	if(SensorValue[leftLineFollower] < 2000 && SensorValue[rightLineFollower] < 2000 && SensorValue[centerLineFollower] > 2000)
	// If the left line follower is white and the right line follower is white and the middle sensor is black
	{
	motor[leftMotor] = speed;//Turn Left Motor
	motor[rightMotor] = speed;//Turn Right Motor
	}
}

void left()//Function to turn left
{
	if(SensorValue[leftLineFollower] < 2000 && SensorValue[rightLineFollower] > 2000 && SensorValue[centerLineFollower] < 2000)
	{//If we see black with the right sensor and not with the left sensor and the middle sensor is white
	motor[leftMotor] = speed;//Turn Left Motor opposite direction
	motor[rightMotor] = -speed;//Turn Right Motor
	}
}

void right()//Function to turn right
{
	if(SensorValue[leftLineFollower] > 2000 && SensorValue[rightLineFollower] < 2000 && SensorValue[centerLineFollower] < 2000)
	{//If we see black with the left sensor and not with the right sensor and the middle sensor is white
	motor[leftMotor] = -speed;//Turn Left Motor opposite direction
	motor[rightMotor] = speed;//Turn Right Motor
	}
}

void stopbot()//Function to stop robot
{
	if(SensorValue[leftLineFollower] > 2000 && SensorValue[rightLineFollower] > 2000 && SensorValue[centerLineFollower] > 2000)
	{//If we see black with the right sensor and with the left sensorand the middle sensor is black
	motor[leftMotor] = 0;//Stop Left Motor
	motor[rightMotor] = 0;//Stop Right Motor
	}
}
