#pragma config(StandardModel, "RVW SWERVEBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/****************************************************
Name: Iniyan Joseph
Period: 3
Date: 3/17/2020
Assignment: Robo Slalom 3 (2 Sensor)
Program Description: Follow a line
Algorithm:
1.If we see black with both the right and left sensor, stop
2.If we see black with the right sensor and not with the left sensor, turn left
3.If we see black with the left sensor and not with the right sensor, turn right
4.If we see black with neither the right and left sensor, go forward
*******************************************************/
//Variables---------------------------------------------
int speed = 70;//Set the speed of the motors
//Functions---------------------------------------------
void straight();//Declare Function to go straight
void left();//Declare Function to go left
void right();//Declare Function to go stop the robot
void stopbot();//Stop the robot
void driftleft();//Function to drift left
void driftright();//Function to drift right

task main()
{
	while(true){
	straight();//Go straight
	left();//Turn Left
	right();//Right
	stopbot();//Stop The Robot
	driftleft();//Function to drift left
	driftright();//Function to drift right
}
}

//Function Glossary-------------------------------------
void straight()//Function to go straight
{
	if(SensorValue[leftLineFollower] < 2000 && SensorValue[rightLineFollower] < 2000)
	// If the left line follower is white and the right line follower is white
	{
	motor[leftMotor] = speed;//Turn Left Motor
	motor[rightMotor] = speed;//Turn Right Motor
	}
}

void left()//Function to turn left
{
	if(SensorValue[leftLineFollower] < 2000 && SensorValue[rightLineFollower] > 2000)
	{//If we see black with the right sensor and not with the left sensor
	motor[leftMotor] = speed;//Turn Left Motor opposite direction
	motor[rightMotor] = -speed;//Turn Right Motor
	}
}

void right()//Function to turn right
{
	if(SensorValue[leftLineFollower] > 2000 && SensorValue[rightLineFollower] < 2000)
	{//If we see black with the left sensor and not with the right sensor
	motor[leftMotor] = -speed;//Turn Left Motor opposite direction
	motor[rightMotor] = speed;//Turn Right Motor
	}
}

void stopbot()//Function to stop robot
{
	if(SensorValue[leftLineFollower] > 2000 && SensorValue[rightLineFollower] > 2000)
	{//If we see black with the right sensor and with the left sensor
	motor[leftMotor] = 0;//Stop Left Motor
	motor[rightMotor] = 0;//Stop Right Motor
	}
}

void driftleft()//Function to drift left
{
	if(SensorValue[leftLineFollower] > 2000 && SensorValue[rightLineFollower] < 2000 && SensorValue[centerLineFollower] >2000)
	{//If the right sensor is dark and the dark sensor is white and the center sensor is black
		motor[leftMotor] = 30;//Spin the left Motor Slowly
		motor[rightMotor] = 50;//Spin the right Motor Slowly
	}
}

void driftright()//Function to drift right
{
	if(SensorValue[leftLineFollower] < 2000 && SensorValue[rightLineFollower] > 2000 && SensorValue[centerLineFollower] >2000)
	//If the left sensor is white and the dark sensor is black and the center sensor is black
	{
		motor[leftMotor] = 50;//Spin Left Motor fast
		motor[rightMotor] = 30;//Spin Right Motor Slowly
	}
}
