#pragma config(StandardModel, "RVW Buggybot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true)
{
	motor[leftMotor] = 127;
	motor[rightMotor] = 127;
}
}
